### ISSUE TITLE
[BUG] Suggestions inside Copilot Chat

### ISSUE THREAD

**Issue by felipfr** [ManuelGil/vscode-nestjs-generator#1]
I believe it to be a bug after updating the last version: NestJs code 'snippets' started to appear within Copilot Chat. After deactivating the extension, Chat behavior returns to normal.

![ss](https://github.com/ManuelGil/vscode-nestjs-generator/assets/99354371/e99544b6-5b85-4007-a3c6-e33e67b78773)

**Comment by ManuelGil** [comment]
Hi @felipfr ,

I understand that the report refers to a different extension, one of my snippet extensions for NestJS, maybe [vscode-nestjs-snippets](https://github.com/ManuelGil/vscode-nestjs-snippets).

I have carefully reviewed your report and it is actually normal VSCode behavior. Apparently Copilot Chat loads all extension nippets that are defined for plain text (In my case the defined scope is plain text and typescript).

This is the first report I have received on this, I could certainly remove plain text support from my extension. However, that doesn't mean it can't happen again with another extension with the same scope.

**Comment by felipfr** [comment]
Thanks for the answer.
I disabled this extension here: https://marketplace.visualstudio.com/items?itemName=imgildev.vscode-nestjs-generator

After doing this, it worked normally again, without any snippet appearing. I don't know what it could be, but if you want, I can record the screen to show you. Or if you know how to disable this behavior in Copilot, I would appreciate it.

**Comment by ManuelGil** [comment]
thank you very much for your information

It is a totally unexpected effect, but apparently the snippets extension is totally dependent on this extension, disabling this one disables both, but you can disable or uninstall the snippets extension without affecting this extension.

![demo](https://github.com/ManuelGil/vscode-nestjs-generator/assets/25472045/121013b9-0a85-495b-be9b-af0807b6e364)

**Comment by ManuelGil** [comment]
Hello @felipfr ,

I am interested in knowing what decision you made to close the issue.

Did you disable or remove the snippets extension? Do you want to continue using that extension but need to remove the plain text scope?

**Comment by felipfr** [comment]
Actually, I uninstalled the Prisma snippets extension and uninstalled the other one along with it.

What setting do I change in Copilot so I can continue using the extension? And if you want, you can close the issue.

**Comment by ManuelGil** [comment]
Unfortunately copilot chat does not have a configuration option for that purpose. It is not something that has to do directly with the development of the extensions I have made but a behavior of Copilot Chat, but it does affect me as the creator.

In such a case, I am forced to remove the plain text scope from all my snippet extensions so I am asking for some time as there are 6 extensions just for NestJS.

I recommend you to transfer your questions to the GitHub Copilot issue tracker while I make changes to my extensions.

**Comment by ManuelGil** [comment]
Hi @felipfr ,

All snippet extensions have been updated to remove the plain text scope. You can use them without them interfering with Copilot Chat.

I would be very grateful if you can give a good rating to the extensions in the marketplace, and if you have any ideas to improve any of the extensions, I am open to comments.
